services:
###> doctrine/doctrine-bundle ###
  database:
    image: alpine:3.18 # Utilisation d'une image alpine légère
    environment:
      SQLITE_DB: ${SQLITE_DB:-blogcms}
      SQLITE_PASSWORD: ${SQLITE_PASSWORD:-!ChangeMe!}
      SQLITE_USER: ${SQLITE_USER:-app}
    healthcheck:
      test: ["CMD", "sqlite3", "/var/${SQLITE_DB:-blogcms}.db", "SELECT 1"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/sqlite/data:rw
      # Vous pouvez également utiliser un montage de répertoire hôte pour éviter de perdre les données
      # - ./docker/db/data:/var/lib/sqlite/data:rw
    command: ["/bin/sh", "-c", "apk add --no-cache sqlite && sqlite3 /var/lib/sqlite/data/${SQLITE_DB:-blogcms}.db"]
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
